### ISSUE TITLE
Always 404

### ISSUE THREAD

**Issue by Vincent-Stragier** [jakbin/py-localtunnel#1]
Hello @jakbin,

I tried your code without success on a Windows machine, and I dived into the code. I made some changes on my fork, but I always have 404 error. I even tried the simple server example you gave in your tutorial without success.

Also, do you know why the programme cannot be quitted via Ctrl + C? It somehow gets stuck, but I don't know why yet.

https://github.com/jakbin/py-localtunnel/compare/main...Vincent-Stragier:py-localtunnel:main

Kind regards,
Vincent

**Comment by jakbin** [comment]
I have tried it. It works fine . But sometimes it gives 404 error.
