### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by Bk073** [jakbin/py-localtunnel#5]
It is working in local. But when trying to run on server, I am getting error.

`pylt port 8081`

`requests.exceptions.ConnectionError: HTTPConnectionPool(host='localtunnel.me', port=80): Max retries exceeded with url: /?new (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fb777790100>: Failed to resolve 'localtunnel.me' ([Errno -3] Temporary failure in name resolution)"))`

Also, I am wondering why `port=80` is taken when I am trying to run 8081 ? 

My server is running is port 8081:

`tcp        0      0 127.0.0.1:8081          0.0.0.0:*               LISTEN      191132/python3   `

**Comment by jakbin** [comment]
Port 80 is localtunnel website port. Basically there is network problem on your system that why you got that error .

**Comment by jakbin** [comment]
@Bk073 did you fix it ??
