### ISSUE TITLE
Reflecting data back to local socket

### ISSUE THREAD

**Issue by SamG101-Developer** [jakbin/py-localtunnel#7]
Hi,

I have written some simple code for the tunnelling:

```python
import os
import socket

import threading
import time

SERVER_PORT = 12345


class Server:
    _sock: socket.socket
    _ssh_address: str

    def __init__(self):
        self._sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self._sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        self._sock.bind(("", SERVER_PORT))
        self._sock.listen(10)

        self._ssh_address = ""
        if os.path.exists("tmp"):
            os.remove("tmp")

        print(f"Server started at {self._sock.getsockname()}")
        threading.Thread(target=self._listen).start()
        threading.Thread(target=self._setup_ssh_tunnel).start()

        while not os.path.exists("tmp"):
            time.sleep(2)
        self._ssh_address = open("tmp").read().split(" ")[-1].strip()
        print(f"SSH tunnelled url: {self._ssh_address}")

    def _setup_ssh_tunnel(self) -> None:
        os.system(f"lt port {SERVER_PORT} --subdomain my-example-subdomain-9843 > tmp")

    def _listen(self) -> None:
        try:
            while True:
                print("Waiting for connection...")
                conn, addr = self._sock.accept()
                print(f"Connection from {addr}")
                message = conn.recv(1024)
                if not message:
                    conn.close()
                    continue

                print(f"Received: {message}")
                conn.sendall(f"HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\n\r\n{message}".encode())
                conn.close()

        except Exception as e:
            self._sock.close()
            print(f"Server stopped {e}")


class Client:
    _sock: socket.socket

    def __init__(self, server_ip):
        server_ip = server_ip.replace("https://", "")

        self._sock = socket.socket()
        self._sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        self._sock.settimeout(5)
        self._sock.connect((server_ip, 80))

        ...

    def __del__(self):
        self._sock.close()


def main():
    server = Server()
    time.sleep(3)
    client = Client(server._ssh_address)


if __name__ == "__main__":
    main()
```

In the `Client` class, I can connect to port 80, send a `GET` request and receive the website contents, but I'd like to be able to send commands to `my-example-subdomain-9843.loca.lt`, which are then sent back to the internal `Server._sock` socket so that I can handle them internally. If I access "localhost:12345" from this machine, the `Server._sock` receives the message (`GET` request).

Is it possible to send commands to the external URL, that are then forwarded to the `Server._sock` socket, and if so, what might I need to change? I've attempted sending things to port 22, which begins an SSH handshake - do I need to manually complete this or is this something else? Thanks.

**Edit**
I have been using Wireshark and noticed that there are lots of re-transmissions happening:
This one
![image](https://github.com/jakbin/py-localtunnel/assets/71029643/6e888bdc-f374-422c-be9c-36d5899756e5)
This one multiple times (at least 3 sets of these)
![image](https://github.com/jakbin/py-localtunnel/assets/71029643/1732d8a7-4ca8-43aa-9da9-9de33d03b5d0)
And finally this one mixed with the previous one)
![image](https://github.com/jakbin/py-localtunnel/assets/71029643/57db7cf1-0f0d-42cd-948e-5f6b89ef2b86)

This may link with:
![image](https://github.com/jakbin/py-localtunnel/assets/71029643/50346524-d785-4c58-955f-3f6009be3948)

When I start the code 1 client joins immediately, but causes these transmission errors. Is it expecting some response from the server socket on startup?

**Comment by jakbin** [comment]
you can not use localtunnel for tcp connections .
